Added checking of version prefix, when do "lerna version"
lerna/lerna pull request #2601
Opened 2020-05-26 17:34 UTC by divomen

A fix for issue https://github.com/lerna/lerna/issues/2056
## Description

Added a math for tagPrefix for collectUpdates in version command (only for fixed-version repo)

## Motivation and Context

The main problem is, that when we use custom tags in a repo, the version command calculates changes from a wrong tag.
Also, there is an open issue: https://github.com/lerna/lerna/issues/2056

## How Has This Been Tested?

I tested it on a real repo.

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2020-05-29 13:52 UTC, divomen commented
> This is awesome. Is it possible to add some tests around this?
> 
> https://github.com/lerna/lerna/blob/7abfe43426197fbc7f18c44b0c994324609fc769/utils/collect-updates/__tests__/collect-updates.test.js

Ok, I'll try

2021-02-11 00:01 UTC, evocateur requested changes
This is definitely an oversight, thank you for identifying it.

I think we need a more holistic solution, as there are actually four places across the Lerna codebase that call `collectUpdates`, and all of them need this awareness.

We also need tests to validate the change, preventing future regression.

2022-05-31 10:47 UTC, gund commented
Any update on this?

This is really a blocker for a cases where Lerna is used multiple times with different tag prefixes and currently will not release anything for subsequent calls after the first one was released...

2022-05-31 10:49 UTC, gund commented on commands/version/index.js
> +      opts.match = `${this.tagPrefix}*`;
It's probably better to use `**` instead to allow for tags that contain forward slashes as a single star will not match those.
```suggestion
      opts.match = `${this.tagPrefix}**`;
```

2022-12-13 11:30 UTC, JamesHenry commented
@divomen are you interested in completing this PR?

@gund I see you applied a more comprehensive version of this change to a fork, are you interested in porting that to the main lerna project to supersede this PR?

2022-12-13 11:43 UTC, closed without merging