fix 2352 by creating symlinks for directories
lerna/lerna pull request #2789
Opened 2021-01-04 07:28 UTC by ericprud

see [bug analysis](https://github.com/lerna/lerna/issues/2352#issuecomment-753682568) for justification

## Description
Removed if which skipped creating symlinks for anything with type "directory".

## Motivation and Context
fixes #2352, #2491 (maybe others?)

## How Has This Been Tested?
Ran `npm test` and `npm run integration` on ubuntu 20.04. No windows testing (counting on CI for that).

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Happy to add [a tarball](http://www.w3.org/2021/01/lerna-PR-2789.tar.gz) if someone gives me guidance on creating new tests.

2021-02-10 23:27 UTC, evocateur requested changes
This needs tests to verify.

A `file:` dependency is already symlinked elsewhere in the tree. Arguably, one does not need to use `lerna bootstrap` when using `file:` dependencies, so that likely explains the absence of breakage when these lines were removed.

2021-02-11 08:42 UTC, ericprud commented
> This needs tests to verify.

The linked [tarball](http://www.w3.org/2021/01/lerna-PR-2789.tar.gz) has a small sample to reproduce this bug and show that the PR fixes it:
```
eric@touchy:~/Downloads$ tar xzf lerna-PR-2789.tar.gz 
eric@touchy:~/Downloads$ tree PR-2789/
PR-2789/
├── lerna.json
├── package.json
└── packages
    ├── bar
    │   └── package.json
    └── foo
        └── package.json
eric@touchy:/tmp/ttt$ cd PR-2789/
eric@touchy:/tmp/ttt/PR-2789$ npm install

up to date, audited 1 package in 232ms

found 0 vulnerabilities
eric@touchy:/tmp/ttt/PR-2789$ npx lerna bootstrap
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 2 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
eric@touchy:/tmp/ttt/PR-2789$ ls packages/bar/
package.json
```
Note no `node_modules` under `packages/bar`. If I patch the code according to this PR, it behaves as expected:
```
eric@touchy:/tmp/ttt/PR-2789$ lerna bootstrap
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 2 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
eric@touchy:/tmp/ttt/PR-2789$ ls packages/bar/
node_modules  package.json
eric@touchy:/tmp/ttt/PR-2789$ ls -l packages/bar/node_modules/\@scope/
total 0
lrwxrwxrwx 1 eric eric 12 févr. 11 09:40 foo -> ../../../foo
```

2021-02-16 06:05 UTC, ericprud commented
Just wondering where this sits as I have a package waiting on it. 

> This needs tests to verify.

I think the [above example](https://github.com/lerna/lerna/pull/2789#issuecomment-777281930) demonstrates both the pathology described in #2352, #2491 and that this PR fixes it. I don't know the lerna test system but would be happy to work with someone to integrate that example into the test suite.

> A `file:` dependency is already symlinked elsewhere in the tree. Arguably, one does not need to use `lerna bootstrap` when using `file:` dependencies, so that likely explains the absence of breakage when these lines were removed.

I think that many people using lerna expect to be able to add unversioned deps to packaged modules and have lerna add the node_modules symlinks as it does with versioned deps. The current work-around for this, as mentioned in the issues is to add a specific version in the file: deps but that means yoiu have to visit those deps when you publish new versions.

2021-07-27 11:36 UTC, Jameskmonger commented
@ericprud I'd be happy to help you try and get some tests around this, if @evocateur would be happy to merge it after that

2021-08-05 15:38 UTC, ericprud commented
Some time about one attention-span ago, someone said in an issue comment that this `file:` approach pays a `lerna-add`-time performance penalty because of duplicate caching in `node_modules` and yarn's `.cache`. That said, I suspect I would pay that cost in order to avoid brittleness associated with the version-specific links currently used by lerna.

@Jameskmonger , Can you provide a skeleton test, perhaps using the tarball referenced at the top of [my earlier comment](https://github.com/lerna/lerna/pull/2789#issuecomment-777281930) and I'll add it to the PR?

2022-11-29 13:56 UTC, JamesHenry commented
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

In this case of this specific PR it doesn't seem to have reached a place of being a clear improvement to the legacy commands, so I think closing is definitely the clearest thing to do.

Many thanks 🙏

2022-11-29 13:56 UTC, closed without merging

2022-12-06 00:29 UTC, ericprud commented
> ...covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

Is there a recipe book for folks who learned lerna in that era and apparently missed out on how to gracefully manage monorepos with e.g. npm?

2022-12-06 10:32 UTC, JamesHenry commented
@ericprud I think you'll find that for the most part things will "just work" and match your intuition. Starting with the main npm docs page to see the simple (and likely familiar) way of configuring `workspaces` with a glob pattern of packages is a good idea: https://docs.npmjs.com/cli/v8/using-npm/workspaces

Once workspaces are wired up, simply running `npm install` from the root handles creating an appropriate package-lock.json file and links all the nested packages to each other to match any defined relationships you already have.

Feel free to open a discussion on here if any aspect of transitioning is particular problematic or confusing and we will try and help you/use it to inform more specific guidance in the future

2022-12-11 10:32 UTC, ericprud commented
> Once workspaces are wired up, simply running `npm install` from the root handles creating an appropriate package-lock.json file and links all the nested packages to each other to match any defined relationships you already have.

(For any others that end up here), does that work with file: references or versioned references?

Lerna publish gave you a choice between keeping everything at the same version (even if that involved publishing stuff that hadn't changed) vs. having heterogenous versions of nested packages. Is there some advice on that front?