fix(package-graph): ensure to touch all nodes
lerna/lerna pull request #3234
Opened 2022-07-07 12:56 UTC by simllll

fixes https://github.com/lerna/lerna/issues/3233

## Description
the fix of not touching a node twice (https://github.com/lerna/lerna/pull/2874/files) has a side effect so that not all scirpts are executed anymore.

this fixes it by still improving / keeping the performance benefits of the other pr.

2022-07-07 13:05 UTC, JamesHenry requested changes
Thanks @simllll, is there a failing test we can add first and fix with this?

2022-07-07 13:05 UTC, JamesHenry commented on core/package-graph/index.js
> +				console.log('topLevelDependent', identifier);
@simllll Please remove the console log

2022-07-07 13:21 UTC, simllll commented on core/package-graph/index.js
> +				console.log('topLevelDependent', identifier);
oha, sorry about that

2022-07-07 13:43 UTC, simllll commented
Okay, I was trying to break it down further, and I guess I found the real issue here: a dependency circle caused this behavior. Even though the circle is unrelated to this package. So it seems it's not really a bug, it's just a hard to find "issue". Sorry for the troubles

2022-07-26 11:39 UTC, simllll commented
I ran into the same thing today again, but now I don't have any circular dependencies.. still not sure what's going on (lerna 5.2.0), but it's for sure that even though the package list on `lerna run build --no-private` says it has exectued the packages, it does not run the commands.

2022-07-26 12:58 UTC, ghiscoding commented
@simllll are you by any chance using the new `useNx`? I might have seem something similar when that option is enabled

2022-07-26 12:58 UTC, simllll commented
Hi @ghiscoding , nope, not using this option

2022-07-26 13:07 UTC, ghiscoding commented
so does this PR fix your latest issue then? if so I'd be willing to push it to Lerna-Lite

2022-07-26 13:09 UTC, simllll commented
It does, but I'm not sure if we losse the performance benefits of the earlier patch with this one again... would be great if the one who created the https://github.com/lerna/lerna/pull/2874 PR can look at this.

2022-08-06 20:32 UTC, ghiscoding commented
I can confirm that #2874 is causing side effect, we ran into this on a large project which had 43 packages changed, it was only returning 5 of them, so that's a pretty big side effect. Your code change seems to work, so I'll apply it into Lerna-Lite unless something better comes up

2022-08-12 13:00 UTC, JamesHenry commented
Based on the feedback above let's get this merged, we'll need to spend some more time trying to understand these changes better though and have some test coverage.

If there are any other issues that get raised then we will likely have to revert the original change

2022-08-12 13:00 UTC, merged