feat: Lerna init default useNx and useWorkspaces to true
lerna/lerna pull request #3255
Opened 2022-07-22 02:31 UTC by fahslaj

When initializing lerna for the first time with `lerna init`, workspaces and nx will both be enabled by default. 

## Description

For lerna init:
- default useNx to true
- default useWorkspaces to true
- automatically add nx as a dev dependency if useNx will be true
- automatically add workspaces property to package.json if useWorkspaces will be true
- explicitly set useNx to false if lerna.json already exists and useNx is not set
- explicitly set useWorkspaces to false if lerna.json already exists and useWorkspaces is not set
- fix a bug where useNx was being reset to false whenever lerna init was run on an existing workspace with useNx: true

For all commands:
- add a warning to the console when a command is run and lerna does not have either:
  - useWorkspaces: true in lerna.json AND a workspaces property set in package.json
  - packages property set in lerna.json
- add a warning to the console when workspaces are defined in package.json, but lerna.json does not have useWorkspaces: true

For the docs:
- updated the getting started guide to no longer describe needing to install nx manually on a newly created lerna project

## Motivation and Context

This change enables two of lerna's most powerful features by default - the ability to run commands with nx and the ability to make use of Yarn/npm workspaces by default for detecting packages.

## How Has This Been Tested?

Extensive unit, integration, and e2e tests have been added. I have also manually tested the lerna init command for each of these scenarios.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-07-22 02:47 UTC, fahslaj commented on commands/init/index.js
> +        if (!this.hasExistingLernaConfig) {
The more I look at this logic, the more I realize that the `ensurePackageJSON` and `ensureLernaConfig` functions should be combined. Both config files are dependent on each other, such as for workspaces support.

2022-07-22 15:58 UTC, JamesHenry requested changes
Per slack discussion

2022-07-22 16:48 UTC, JamesHenry approved these changes

2022-07-22 16:48 UTC, merged

2022-07-23 01:38 UTC, AviVahl commented
This installs `nx` and its many dependencies (some of which are requesting exact versions) to any project using lerna, even if they don't use `nx`. :-1: 

Even stuff that I wouldn't expect like `tsconfig-paths` and `@parcel/watcher` are now being installed.