feat(version): sync the version of the package contents
lerna/lerna pull request #3787
Opened 2023-07-19 00:40 UTC by matheo

## Description

Usually in our CI we do `lint` -> `test` -> `built` -> `publish`  
but it has been a pain to build package contents  
and then sync the generated version by `lerna publish` with a root hook.

## Motivation and Context

In case we configure a publish directory different than the source folder  
we will need a custom script to sync the new version, otherwise the old version will be published.

## How Has This Been Tested?

I've tested it in my monorepo with the build output of this branch and it worked:

![image](https://github.com/lerna/lerna/assets/260185/135c4ba8-ef1e-4644-858c-b9b1e2ac86a5)

the config interpolation happens earlier than before and sync the `dist` output.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-07-31 02:09 UTC, matheo commented
@fahslaj @JamesHenry I just found out that `lerna bootstrap` takes in account the package.json `publishConfig.directory` and it's like a central build's `options.outputPath` that should not be configured on command basis but just a single time like in the old bootstrap days.

2023-07-31 14:18 UTC, Lkhmom85 approved these changes

2023-08-12 16:46 UTC, matheo commented on libs/commands/publish/src/index.ts
> +
@fahslaj I just moved this code before `versionCommand` so it has the `contents` resolved to update the package version there with `syncDistVersion`

2023-08-16 15:36 UTC, fahslaj commented on libs/core/src/lib/package.ts
> +  syncDistVersion() {
As mentioned in my review, this function can be converted to use `async/await` instead of `Promise.resolve` and `.then` chaining.

2023-08-17 05:24 UTC, matheo commented
@fahslaj I've tried to run `e2e-publish` locally with no luck, I may need help with the wording :thinking: 

hopefully the e2e works without the conventional commit of my setup,
and I'd like to know what's inside the `test-main` branch because I have no idea of the package `build` setup
and we need to be sure that after building the package, `lerna publish` bumps both `package.json` files

2023-08-17 20:59 UTC, matheo commented
@fahslaj I get a weird `init: required argument missing` https://cloud.nx.app/runs/TQp7pFoPgJ

my e2e test should be fine tho, perhaps I don't know which bump will be used without conventional commits :thinking:

2023-08-24 02:25 UTC, fahslaj commented
@matheo I've discovered a few things missing from the new e2e test. Can you please ensure that "allow edits by maintainers" is checked on the PR so I can push the fixes?

<img width="292" alt="image" src="https://github.com/lerna/lerna/assets/6913035/c06ccc1a-c82f-408e-ba3b-701151d2c34f">

Specifically, what is missing is that the publish command needs to provide a version:
`publish ${version} --registry=http://localhost:4872 --loglevel verbose --concurrency 1 -y`

This version also needs to be set in `packages/package-1/package.json`, then `packages/package-1/package.json` needs to be copied to the dist directory.

2023-08-28 01:09 UTC, matheo commented
@fahslaj maintainers allowed now :)

I'm updating the version number only to the "output" folder because sometimes we have executors like `@nx/angular` that generates more output via `ng-packagr` in the `package.json` file so we cannot override it completely.

2023-08-28 16:23 UTC, fahslaj requested changes
@matheo for some reason, I was still unable to push to this PR. Instead I've added the changes I've made to the e2e test as comment suggestions. When you get a chance, try those changes and let me know if it still fails for you.

2023-08-28 16:23 UTC, fahslaj commented on e2e/publish/src/custom-publish-directories.spec.ts
> +      }));
```suggestion
      const version = randomVersion();

      await fixture.lerna("create package-1 -y");
      await fixture.updateJson("packages/package-1/package.json", (pkg) => ({
        ...pkg,
        main: "main.js",
        version,
        scripts: {
          build: "cp ./lib/package-1.js ../../dist/packages/package-1/lib/main.js",
          copyManifest: "cp ./package.json ../../dist/packages/package-1/package.json",
        },
      }));
```

2023-08-28 16:23 UTC, fahslaj commented on e2e/publish/src/custom-publish-directories.spec.ts
> +
```suggestion
      const distVersion = JSON.parse(
        await fixture.readWorkspaceFile("dist/packages/package-1/package.json")
      ).version;
```

2023-08-30 04:42 UTC, matheo commented
@fahslaj Ok, I've synced your changes except `copyManifest` because that's supposed to be done by `lerna publish --sync-dist-version`, Let's see if e2e passes now

2023-08-30 12:00 UTC, fahslaj commented
It also appears that CI is failing due to code formatting. Be sure to run `npx nx format:check` and then `npx nx format:write` to make sure the changes match the formatting standards.

2023-08-30 21:34 UTC, fahslaj approved these changes
Thank you @matheo !

2023-08-30 21:35 UTC, merged