fix(docs): remove mention of useWorkspaces
lerna/lerna pull request #3986
Opened 2024-04-01 18:25 UTC by kevinji

## Description
`useWorkspaces` has been removed since 7.0.0 and should not be mentioned.

## Motivation and Context
Mentioning `useWorkspaces` is confusing as it has been removed.

## How Has This Been Tested?
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (change that has absolutely no effect on users)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-01 18:37 UTC, JamesHenry requested changes

2024-04-01 18:37 UTC, JamesHenry commented on website/docs/recipes/using-pnpm-with-lerna.md
> +- ignore `packages:` in `package.json
```suggestion
- ignore `"workspaces": []` in `package.json`
```

2024-04-03 19:27 UTC, kevinji commented
@JamesHenry anything else that needs to be updated other than the change you made?

2024-04-04 09:42 UTC, merged

2024-04-04 09:42 UTC, JamesHenry commented
Thank you @kevinji